// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/microtest/microtest.proto

package go_micro_srv_microtest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Microtest service

type MicrotestService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Microtest_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Microtest_PingPongService, error)
}

type microtestService struct {
	c    client.Client
	name string
}

func NewMicrotestService(name string, c client.Client) MicrotestService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.microtest"
	}
	return &microtestService{
		c:    c,
		name: name,
	}
}

func (c *microtestService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Microtest.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microtestService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Microtest_StreamService, error) {
	req := c.c.NewRequest(c.name, "Microtest.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &microtestServiceStream{stream}, nil
}

type Microtest_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type microtestServiceStream struct {
	stream client.Stream
}

func (x *microtestServiceStream) Close() error {
	return x.stream.Close()
}

func (x *microtestServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microtestServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microtestServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *microtestService) PingPong(ctx context.Context, opts ...client.CallOption) (Microtest_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Microtest.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microtestServicePingPong{stream}, nil
}

type Microtest_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type microtestServicePingPong struct {
	stream client.Stream
}

func (x *microtestServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *microtestServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microtestServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microtestServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *microtestServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Microtest service

type MicrotestHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Microtest_StreamStream) error
	PingPong(context.Context, Microtest_PingPongStream) error
}

func RegisterMicrotestHandler(s server.Server, hdlr MicrotestHandler, opts ...server.HandlerOption) error {
	type microtest interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Microtest struct {
		microtest
	}
	h := &microtestHandler{hdlr}
	return s.Handle(s.NewHandler(&Microtest{h}, opts...))
}

type microtestHandler struct {
	MicrotestHandler
}

func (h *microtestHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MicrotestHandler.Call(ctx, in, out)
}

func (h *microtestHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicrotestHandler.Stream(ctx, m, &microtestStreamStream{stream})
}

type Microtest_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type microtestStreamStream struct {
	stream server.Stream
}

func (x *microtestStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microtestStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microtestStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microtestStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *microtestHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MicrotestHandler.PingPong(ctx, &microtestPingPongStream{stream})
}

type Microtest_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type microtestPingPongStream struct {
	stream server.Stream
}

func (x *microtestPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *microtestPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microtestPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microtestPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *microtestPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
